name: Sync Branch with Main into Sub-Folder

on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: choice
        description: 'Name of the branch to sync with main'
        required: true
        options:
          - server-web
          - client-web
          - client-windows

jobs:
  sync_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git identity
        run: |
          git config --global user.email "joe@brownboxstudio.com"
          git config --global user.name "joegutman"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List branches
        run: git branch

      - name: Sync Branch Files
        run: |
          branch_folder_name="$(echo ${{ github.event.inputs.branch-name }} | sed 's/-/_/g')"
          mkdir -p $branch_folder_name
          cd $branch_folder_name
          git checkout ${{ github.event.inputs.branch-name }} -- '*'

      - name: List copied files
        run: ls -l
